env:
  - GO111MODULE=on
  - GOPROXY=https://goproxy.io,direct

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
    ldflags:
      - -w -X github.com/zackijack/go-project/internal/version.Version={{ .Version }} -X github.com/zackijack/go-project/internal/version.GitCommit={{ .Commit }} -X github.com/zackijack/go-project/internal/version.BuildDate={{ .Date }}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-{{.ShortCommit}}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - Merge pull request
      - Merge branch
      - go mod tidy

brews:
  - tap:
      owner: zackijack
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/zackijack/go-project
    description: Go project template
    install: |
      bin.install "go-project"

      output = Utils.safe_popen_read({ "SHELL" => "bash" }, bin/"go-project", "completion", "bash")
      (bash_completion/"go-project").write output

      output = Utils.safe_popen_read({ "SHELL" => "zsh" }, bin/"go-project", "completion", "zsh")
      (zsh_completion/"_go-project").write output
    test: |
      system "#{bin}/go-project version"

nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Arch }}"
    homepage: https://github.com/zackijack/go-project
    description: Go project template
    formats:
      - deb
      - rpm

dockers:
  - image_templates:
      - "zackijack/go-project:{{ .Tag }}"
      - "zackijack/go-project:v{{ .Major }}"
      - "zackijack/go-project:v{{ .Major }}.{{ .Minor }}"
      - "zackijack/go-project:latest"
    dockerfile: Dockerfile
    use_buildx: true
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url=https://github.com/zackijack/go-project"
      - "--label=org.opencontainers.image.source=https://github.com/zackijack/go-project"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--cache-from=type=local,src=/tmp/.buildx-cache"
      - "--cache-to=type=local,dest=/tmp/.buildx-cache"
